import {
  pgTable,
  text,
  timestamp,
  uuid,
  jsonb,
  varchar,
  pgEnum,
  boolean,
  index,
  integer,
} from 'drizzle-orm/pg-core';
import { users } from './schema';

/**
 * INBOX SCHEMA
 *
 * Database schema for Flowent Inbox v2:
 * - Inbox Threads (conversations with agents)
 * - Inbox Messages (individual messages in threads)
 * - Artifacts (code, documents, email drafts generated by agents)
 */

// =====================================================
// ENUMS
// =====================================================

export const threadStatusEnum = pgEnum('thread_status', [
  'active',      // Normal conversation in progress
  'suspended',   // Waiting for human approval
  'completed',   // Conversation finished
  'archived'     // Archived thread
]);

export const threadPriorityEnum = pgEnum('thread_priority', [
  'low',
  'medium',
  'high',
  'urgent'
]);

export const messageTypeEnum = pgEnum('inbox_message_type', [
  'text',              // Regular text message
  'approval_request',  // HITL approval request
  'system_event',      // System events (handoffs, workflow updates)
  'artifact'           // Message with artifact reference
]);

export const messageRoleEnum = pgEnum('message_role', [
  'user',
  'agent',
  'system'
]);

export const artifactTypeEnum = pgEnum('artifact_type', [
  'code',         // Code snippets/files
  'markdown',     // Markdown documents
  'email_draft',  // Email drafts
  'data_table',   // Table/spreadsheet data
  'json',         // JSON data
  'html'          // HTML content
]);

export const approvalActionTypeEnum = pgEnum('approval_action_type', [
  'send_email',
  'external_api_call',
  'database_write',
  'file_operation',
  'budget_spend',
  'other'
]);

export const approvalStatusDbEnum = pgEnum('approval_status_db', [
  'pending',
  'approved',
  'rejected',
  'expired'
]);

// =====================================================
// INBOX THREADS TABLE
// =====================================================

export const inboxThreads = pgTable('inbox_threads', {
  id: uuid('id').primaryKey().defaultRandom(),

  // User & Workspace
  userId: varchar('user_id', { length: 255 }).notNull(),
  workspaceId: uuid('workspace_id'),

  // Thread Info
  subject: varchar('subject', { length: 500 }).notNull(),
  preview: text('preview'), // Last message preview

  // Agent Info
  agentId: varchar('agent_id', { length: 50 }).notNull(),
  agentName: varchar('agent_name', { length: 100 }).notNull(),

  // Status
  status: threadStatusEnum('status').notNull().default('active'),
  priority: threadPriorityEnum('priority').notNull().default('medium'),

  // Counters
  unreadCount: integer('unread_count').notNull().default(0),
  messageCount: integer('message_count').notNull().default(0),

  // Approval tracking
  pendingApprovalId: uuid('pending_approval_id'),

  // Metadata
  metadata: jsonb('metadata').$type<{
    workflowId?: string;
    executionId?: string;
    tags?: string[];
    context?: Record<string, unknown>;
  }>().notNull().default({}),

  // Timestamps
  lastMessageAt: timestamp('last_message_at').notNull().defaultNow(),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
}, (table) => ({
  userIdIdx: index('inbox_thread_user_id_idx').on(table.userId),
  workspaceIdIdx: index('inbox_thread_workspace_id_idx').on(table.workspaceId),
  agentIdIdx: index('inbox_thread_agent_id_idx').on(table.agentId),
  statusIdx: index('inbox_thread_status_idx').on(table.status),
  lastMessageAtIdx: index('inbox_thread_last_message_at_idx').on(table.lastMessageAt),
  userStatusIdx: index('inbox_thread_user_status_idx').on(table.userId, table.status),
}));

// =====================================================
// INBOX MESSAGES TABLE
// =====================================================

export const inboxMessages = pgTable('inbox_messages', {
  id: uuid('id').primaryKey().defaultRandom(),

  // Thread Reference
  threadId: uuid('thread_id').notNull().references(() => inboxThreads.id, { onDelete: 'cascade' }),

  // Message Content - using varchar to match existing DB schema
  role: varchar('role', { length: 20 }).notNull(),
  type: varchar('type', { length: 30 }).notNull().default('text'),
  content: text('content').notNull(),

  // Attachments & Artifacts (existing in DB)
  attachments: jsonb('attachments').default([]),
  artifacts: jsonb('artifacts').default([]),

  // Approval Data (if type = 'approval_request')
  approval: jsonb('approval').$type<{
    approvalId: string;
    actionType: string;
    status: 'pending' | 'approved' | 'rejected' | 'expired';
    cost?: number;
    estimatedTokens?: number;
    payload?: Record<string, unknown>;
    previewData?: string;
    expiresAt?: string;
    resolvedAt?: string;
    resolvedBy?: string;
    comment?: string;
  }>(),

  // System Event Metadata (if type = 'system_event')
  metadata: jsonb('metadata').$type<{
    eventType?: string;
    workflowName?: string;
    fromAgent?: string;
    toAgent?: string;
    reason?: string;
    details?: string;
    agentName?: string;
    agentId?: string;
    action?: string;
    approvedBy?: string;
    priority?: string;
    toolCalls?: Array<{ id: string; name: string; status: string; input?: Record<string, unknown>; output?: Record<string, unknown> }>;
    model?: string;
    tokens?: number;
  }>(),

  // Timestamps
  timestamp: timestamp('timestamp').notNull().defaultNow(),
  createdAt: timestamp('created_at').notNull().defaultNow(),
}, (table) => ({
  threadIdIdx: index('inbox_message_thread_id_idx').on(table.threadId),
  roleIdx: index('inbox_message_role_idx').on(table.role),
  typeIdx: index('inbox_message_type_idx').on(table.type),
  timestampIdx: index('inbox_message_timestamp_idx').on(table.timestamp),
  threadTimestampIdx: index('inbox_message_thread_timestamp_idx').on(table.threadId, table.timestamp),
}));

// =====================================================
// ARTIFACTS TABLE
// =====================================================

export const artifacts = pgTable('artifacts', {
  id: uuid('id').primaryKey().defaultRandom(),

  // References
  threadId: uuid('thread_id').references(() => inboxThreads.id, { onDelete: 'set null' }),
  messageId: uuid('message_id').references(() => inboxMessages.id, { onDelete: 'set null' }),
  workflowExecutionId: uuid('workflow_execution_id'), // Optional link to workflow

  // Artifact Content
  type: artifactTypeEnum('type').notNull(),
  title: varchar('title', { length: 500 }).notNull(),
  content: text('content').notNull(), // The actual heavy payload

  // Code-specific fields
  language: varchar('language', { length: 50 }), // e.g., 'typescript', 'python'

  // Version Control
  version: integer('version').notNull().default(1),
  parentArtifactId: uuid('parent_artifact_id'), // For versioning

  // Metadata
  metadata: jsonb('metadata').$type<{
    lineCount?: number;
    wordCount?: number;
    fileSize?: number;
    encoding?: string;
    mimeType?: string;
    createdBy?: string;
    agentId?: string;
    agentName?: string;
    workflowStep?: string;
    tags?: string[];
  }>().notNull().default({}),

  // Ownership
  userId: varchar('user_id', { length: 255 }).notNull(),
  workspaceId: uuid('workspace_id'),

  // Timestamps
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
}, (table) => ({
  threadIdIdx: index('artifact_thread_id_idx').on(table.threadId),
  messageIdIdx: index('artifact_message_id_idx').on(table.messageId),
  workflowExecutionIdIdx: index('artifact_workflow_execution_id_idx').on(table.workflowExecutionId),
  typeIdx: index('artifact_type_idx').on(table.type),
  userIdIdx: index('artifact_user_id_idx').on(table.userId),
  workspaceIdIdx: index('artifact_workspace_id_idx').on(table.workspaceId),
  createdAtIdx: index('artifact_created_at_idx').on(table.createdAt),
  parentArtifactIdx: index('artifact_parent_artifact_id_idx').on(table.parentArtifactId),
}));

// =====================================================
// INBOX APPROVALS TABLE
// =====================================================

/**
 * NOTE: This schema matches the ACTUAL database structure.
 * The actual DB uses:
 * - action_details (jsonb) instead of payload
 * - workflow_id + workflow_name instead of workflowExecutionId
 * - No preview_data column
 * - Different nullability constraints
 */
export const inboxApprovals = pgTable('inbox_approvals', {
  id: uuid('id').primaryKey().defaultRandom(),

  // References (nullable in actual DB)
  threadId: uuid('thread_id').references(() => inboxThreads.id, { onDelete: 'cascade' }),
  messageId: uuid('message_id').references(() => inboxMessages.id, { onDelete: 'cascade' }),

  // Workflow Integration (actual DB structure)
  workflowId: uuid('workflow_id'),
  workflowName: varchar('workflow_name', { length: 255 }),

  // Approval Info (varchar in actual DB, not enum)
  actionType: varchar('action_type', { length: 50 }),
  status: varchar('status', { length: 20 }).default('pending'),

  // Action Payload (actual column is action_details, not payload)
  actionDetails: jsonb('action_details').$type<{
    toolAction?: string;
    params?: Record<string, unknown>;
    estimatedCost?: number;
    metadata?: {
      icon?: string;
      color?: string;
      label?: string;
      description?: string;
      agentHint?: string;
    };
    previewData?: string;
  }>().default({}),

  // Resolution
  resolvedBy: uuid('resolved_by'),
  resolvedAt: timestamp('resolved_at'),
  comment: text('comment'),

  // Expiration
  expiresAt: timestamp('expires_at'),

  // Timestamps
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
}, (table) => ({
  threadIdIdx: index('inbox_approval_thread_id_idx').on(table.threadId),
  messageIdIdx: index('inbox_approval_message_id_idx').on(table.messageId),
  statusIdx: index('inbox_approval_status_idx').on(table.status),
  expiresAtIdx: index('inbox_approval_expires_at_idx').on(table.expiresAt),
  createdAtIdx: index('inbox_approval_created_at_idx').on(table.createdAt),
}));

// =====================================================
// TYPE EXPORTS
// =====================================================

export type InboxThread = typeof inboxThreads.$inferSelect;
export type NewInboxThread = typeof inboxThreads.$inferInsert;

export type InboxMessage = typeof inboxMessages.$inferSelect;
export type NewInboxMessage = typeof inboxMessages.$inferInsert;

export type Artifact = typeof artifacts.$inferSelect;
export type NewArtifact = typeof artifacts.$inferInsert;

export type InboxApproval = typeof inboxApprovals.$inferSelect;
export type NewInboxApproval = typeof inboxApprovals.$inferInsert;
