'use client';

/**
 * Glass Cockpit - Document Card
 * Renders a compact preview for legal documents generated by Lex.
 * Shows title, section count, word count, and preview toggle.
 */

import { memo, useState } from 'react';
import { FileText, ChevronDown, ChevronUp, Scale, Copy, Check } from 'lucide-react';
import { cn } from '@/lib/utils';
import ReactMarkdown from 'react-markdown';

interface ToolCallData {
  id: string;
  name: string;
  status: 'pending' | 'running' | 'completed' | 'failed';
  result?: {
    success?: boolean;
    data?: {
      document?: string;
      sections?: string[];
      title?: string;
      disclaimer?: string;
      formatted_output?: string;
    };
  };
}

interface DocumentCardProps {
  tool: ToolCallData;
}

function DocumentCardComponent({ tool }: DocumentCardProps) {
  const [expanded, setExpanded] = useState(false);
  const [copied, setCopied] = useState(false);

  const data = tool.result?.data;
  if (!data?.document && !data?.formatted_output) return null;

  const documentText = data.document || data.formatted_output || '';
  const sections = data.sections || [];
  const title = data.title || sections[0] || 'Rechtsdokument';

  // Count words
  const wordCount = documentText.split(/\s+/).filter(Boolean).length;
  const sectionCount = sections.length || documentText.split(/^#{1,3}\s/m).length - 1;

  // Format word count
  const formatWordCount = (count: number) => {
    if (count >= 1000) return `~${(count / 1000).toFixed(1)}k`;
    return `~${count}`;
  };

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(documentText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (e) {
      console.error('Copy failed:', e);
    }
  };

  return (
    <div className="mt-2 rounded-xl overflow-hidden bg-zinc-900/60 border border-white/5 border-l-2 border-l-slate-500">
      {/* Header */}
      <div className="flex items-center gap-2.5 px-4 py-3 bg-zinc-800/40">
        <div className="w-8 h-8 rounded-lg bg-slate-700/50 flex items-center justify-center flex-shrink-0">
          <FileText className="w-4 h-4 text-slate-300" />
        </div>
        <div className="flex-1 min-w-0">
          <h4 className="text-sm font-medium text-zinc-200 truncate">{title}</h4>
          <div className="flex items-center gap-2 mt-0.5">
            <span className="text-[10px] text-zinc-500">
              {sectionCount > 0 ? `${sectionCount} Abschnitte` : 'Dokument'}
            </span>
            <span className="text-[10px] text-zinc-600">·</span>
            <span className="text-[10px] text-zinc-500">
              {formatWordCount(wordCount)} Wörter
            </span>
          </div>
        </div>
        <div className="flex items-center gap-1">
          <button
            onClick={copyToClipboard}
            className="p-1.5 rounded-md hover:bg-zinc-700/50 transition-colors text-zinc-500 hover:text-zinc-300"
            title="Dokument kopieren"
          >
            {copied ? (
              <Check className="w-3.5 h-3.5 text-emerald-400" />
            ) : (
              <Copy className="w-3.5 h-3.5" />
            )}
          </button>
          <button
            onClick={() => setExpanded(!expanded)}
            className="p-1.5 rounded-md hover:bg-zinc-700/50 transition-colors text-zinc-500 hover:text-zinc-300"
            title={expanded ? 'Einklappen' : 'Vorschau'}
          >
            {expanded ? (
              <ChevronUp className="w-3.5 h-3.5" />
            ) : (
              <ChevronDown className="w-3.5 h-3.5" />
            )}
          </button>
        </div>
      </div>

      {/* Expandable Preview */}
      {expanded && (
        <div className="px-4 py-3 border-t border-white/5 max-h-[400px] overflow-y-auto">
          <div className="prose prose-invert prose-sm max-w-none prose-headings:text-zinc-200 prose-p:text-zinc-400 prose-strong:text-zinc-300 prose-li:text-zinc-400">
            <ReactMarkdown>
              {documentText.length > 3000
                ? documentText.substring(0, 3000) + '\n\n---\n\n*[Dokument gekürzt — Volltext über Kopieren-Button verfügbar]*'
                : documentText}
            </ReactMarkdown>
          </div>
        </div>
      )}

      {/* Disclaimer */}
      {data.disclaimer && (
        <div className="px-4 py-2 border-t border-white/5 bg-amber-500/5">
          <div className="flex items-start gap-1.5">
            <Scale className="w-3 h-3 text-amber-500/70 mt-0.5 flex-shrink-0" />
            <p className="text-[10px] text-amber-500/70 leading-relaxed">
              {data.disclaimer}
            </p>
          </div>
        </div>
      )}
    </div>
  );
}

export const DocumentCard = memo(DocumentCardComponent);
